---
driver:
  name: docker

provisioner:
  name: policyfile_zero
  require_chef_omnibus: true

devices:
  - /home/rhass/src/timemasheen:/srv

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    attributes:
